# Generated by Django 3.2.7 on 2021-10-01 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(default='2020-10-10'),
            preserve_default=False,
        ),
    ]
